<img src="http://hilpisch.com/tpq_logo.png" alt="The Python Quants" width="35%" align="right" border="0"><br>

# Python for Finance (2nd ed.)

**Mastering Data-Driven Finance**

&copy; Dr. Yves J. Hilpisch | The Python Quants GmbH

<img src="http://hilpisch.com/images/py4fi_2nd_shadow.png" width="300px" align="left">

# Numerical Computing with NumPy
Although the Python interpreter itself already brings a rich variety of data structures
with it, NumPy and other libraries add to these in a valuable fashion. This chapter
focuses on NumPy, which provides a multidimensional array object to store homogeneous or heterogeneous data arrays and supports vectorization of code.

NumPy, short for Numerical Python, serves as the cornerstone for various scientific and numerical computations in the Python programming language. Given that machine learning revolves around transforming data into numerical representations and subsequently deciphering patterns, NumPy frequently plays a significant role in this context.

In Python, both arrays and NumPy arrays are used to store collections of data, but they have key differences:
Data Type:

Arrays:
Python's built-in array module creates arrays that store elements of a single data type. You specify the type when creating the array, and it can't be changed. This makes them efficient for storing homogeneous data.
NumPy Arrays:
NumPy arrays (ndarray) can also store elements of a single data type, but they are more flexible. NumPy automatically handles type casting when possible, allowing you to mix data types in some cases.

Functionality:

Arrays:
The array module offers basic operations like appending, extending, and removing elements. However, it lacks advanced mathematical and scientific operations.

NumPy Arrays:
NumPy provides a vast array of functions for mathematical operations, linear algebra, Fourier transforms, random number generation, and much more. This makes them ideal for scientific computing and data analysis.

Performance:

Arrays:
Python arrays are not optimized for performance, especially for large datasets.

NumPy Arrays:
NumPy arrays are implemented in C, making them significantly faster than Python arrays for most operations. They also use less memory, which is crucial for handling large datasets.

Broadcasting:

Arrays: Python arrays do not support broadcasting.

NumPy Arrays: NumPy arrays support broadcasting, which allows you to perform operations on arrays with different shapes as long as certain rules are met.

If you are curious how NumPy achieves speed, it is by using process called Vectorization. Vectorization allows operations to be applied on whole arrays/data structures instead of individual elements. Which will avoid loops as loops will cause bottlenecks. NumPy achieves vectorization through a process called broadcasting.

What will we Learn?

Below are the topics we will learn in this blog regarding NumPy:

NumPy datatypes & attributes (ndarray)

Creating arrays

Viewing arrays & matrices

Manipulating & comparing arrays

Sorting arrays

Use cases

While learning above topics we will see most useful functions used in NumPy.


Overall, NumPy arrays are the preferred choice for most data science and numerical computing tasks due to their superior performance, functionality, and flexibility.
Here's an example to illustrate the difference in performance:


In [5]:
import array
import numpy as np
import time

# Create a Python array and a NumPy array
python_array = array.array('i', range(1000000))
numpy_array = np.arange(1000000)

# Time the sum operation for Python array
start_time = time.time()
sum(python_array)
end_time = time.time()
print("Python array sum time:", end_time - start_time)

# Time the sum operation for NumPy array
start_time = time.time()
np.sum(numpy_array)
end_time = time.time()
print("NumPy array sum time:", end_time - start_time)

Python array sum time: 0.011853218078613281
NumPy array sum time: 0.0002570152282714844


## Arrays with Python Lists

In [8]:
v = [0.5, 0.75, 1.0, 1.5, 2.0]  

In [10]:
# a matrix of numbers
m = [v, v, v]  
m  

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [12]:
# One can also easily select rows via simple indexing or single elements via double indexing
m[1]

[0.5, 0.75, 1.0, 1.5, 2.0]

In [14]:
m[1][0]

0.5

In [16]:
# Nesting can be pushed further for even more general structures:
v1 = [0.5, 1.5]
v2 = [1, 2]
m = [v1, v2]
c = [m, m]  
c

[[[0.5, 1.5], [1, 2]], [[0.5, 1.5], [1, 2]]]

In [18]:
# Cube of numbers.
c[0][0][1]

1.5

In [20]:
v = [0.5, 0.75, 1.0, 1.5, 2.0]
m = [v, v, v]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [22]:
# Now change the value of the first element of the v object and see what happens to the m object:
v[0] = 'Python'
m

[['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0]]

## Regular NumPy Arrays
Composing array structures with list objects works, somewhat. But it is not really convenient, and the list class has not been built with this specific goal in mind. It has rather a much broader and more general scope. The array class is a bit more specialized, providing some useful features for working with arrays of data. However, a truly specialized class could be really beneficial to handle array-type structures.

### The Basics
numpy.ndarray is just such a class, built with the specific goal of handling ndimensional arrays both conveniently and efficiently—i.e., in a highly performant manner. The basic handling of instances of this class is again best illustrated by examples:

In [26]:
import numpy as np  

In [28]:
# Creates an ndarray object out of a list object with floats.
a = np.array([0, 0.5, 1.0, 1.5, 2.0])  
a

array([0. , 0.5, 1. , 1.5, 2. ])

In [30]:
type(a)  

numpy.ndarray

In [32]:
# Creates an ndarray object out of a list object with strs.
a = np.array(['a', 'b', 'c'])  
a

array(['a', 'b', 'c'], dtype='<U1')

In [34]:
# np.arange() works similar to range()
a = np.arange(2, 20, 2)  
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [36]:
# … but takes as additional input the dtype parameter.
a = np.arange(8, dtype=float)  
a

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [38]:
# With one-dimensional ndarray objects, indexing works as usual.
a[5:]  

array([5., 6., 7.])

In [40]:
a[:2]  

array([0., 1.])

In [42]:
# A major feature of the ndarray class is the multitude of built-in methods. For instance:
# The sum of all elements
a.sum()  

28.0

In [44]:
# The standard deviation of the elements
a.std()  

2.29128784747792

In [46]:
# The cumulative sum of all elements (starting at index position 0).
a.cumsum()  

array([ 0.,  1.,  3.,  6., 10., 15., 21., 28.])

In [48]:
# Another major feature is the (vectorized) mathematical operations defined on ndarray objects:
# Scalar multiplication with list objects leads to a repetition of elements.
l = [0., 0.5, 1.5, 3., 5.]
2 * l  

[0.0, 0.5, 1.5, 3.0, 5.0, 0.0, 0.5, 1.5, 3.0, 5.0]

In [50]:
a

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [52]:
# By contrast, working with ndarray objects implements a proper scalar multiplication.
2 * a  

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14.])

In [54]:
# This calculates element-wise the square values.
a ** 2  

array([ 0.,  1.,  4.,  9., 16., 25., 36., 49.])

In [56]:
# This interprets the elements of the ndarray as the powers.
2 ** a  

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128.])

In [58]:
# This calculates the power of every element to itself
a ** a  

array([1.00000e+00, 1.00000e+00, 4.00000e+00, 2.70000e+01, 2.56000e+02,
       3.12500e+03, 4.66560e+04, 8.23543e+05])

### Multiple Dimensions
The transition to more than one dimension is seamless, and all features presented so far carry over to the more general cases. In particular, the indexing system is made consistent across all dimensions:

In [61]:
# Constructs a two-dimensional ndarray object out of the one-dimensional one.
b = np.array([a, a * 2])  
b

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 0.,  2.,  4.,  6.,  8., 10., 12., 14.]])

In [63]:
# Selects the first row.
b[0]  

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [65]:
# Selects the third element in the first row; indices are separated, within the brackets, by a comma.
b[0, 2]  

2.0

In [67]:
# Selects the second column.
b[:, 1]

array([1., 2.])

In [69]:
# Selects the first row.
b[0, :]

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [71]:
# Calculates the sum of all values.
b.sum()  

84.0

In [73]:
# Calculates the sum along the first axis; i.e., column-wise.
b.sum(axis=0)  

array([ 0.,  3.,  6.,  9., 12., 15., 18., 21.])

In [75]:
# Calculates the sum along the second axis; i.e., row-wise.
b.sum(axis=1)  

array([28., 56.])

### Exercise:

In [78]:
# The standard way to import NumPy:
import numpy as np

# Create a 2-D array, set every second element in
# some rows and find max per row:

x = np.arange(15, dtype=np.int64).reshape(3, 5)
x[1:, ::2] = -99
x

array([[  0,   1,   2,   3,   4],
       [-99,   6, -99,   8, -99],
       [-99,  11, -99,  13, -99]])

In [80]:
x.max(axis=1)

array([ 4,  8, 13])

### Note:
There are a number of ways to initialize (instantiate) ndarray objects. One is as presented before, via np.array. However, this assumes that all elements of the array are already available. In contrast, one might like to have the ndarray objects instantiated first to populate them later with results generated during the execution of code. To this end, one can use the following functions:

the order parameter: Whether to store multi-dimensional data in row-wise (C-style) or column-wise (Fortran-style) order in memory.

In [83]:
# Creates an ndarray object prepopulated with zeros.
c = np.zeros((2, 3), dtype='i', order='C')  
c

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [85]:
# Creates an ndarray object prepopulated with ones.
c = np.ones((2, 3, 4), dtype='i', order='C')  
c

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [87]:
# Creates a square matrix as an ndarray object with the diagonal populated by ones.
np.eye(5)  

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [89]:
# Creates a one-dimensional ndarray object with evenly spaced intervals between numbers;
# parameters used are start, end, and num (number of elements).
g = np.linspace(5, 15, 12) 
g

array([ 5.        ,  5.90909091,  6.81818182,  7.72727273,  8.63636364,
        9.54545455, 10.45454545, 11.36363636, 12.27272727, 13.18181818,
       14.09090909, 15.        ])

### Note
Here, it becomes obvious how NumPy specializes the construction of arrays with the ndarray class, in comparison to the list -based approach:

• The ndarray object has built-in dimensions (axes).

• The ndarray object is immutable; its length (size) is fixed.

• It only allows for a single data type (np.dtype) for the whole array.

The array class by contrast shares only the characteristic of allowing for a single data
type (type code, dtype).

### Meta-Information
Every ndarray object provides access to a number of useful attributes:

In [93]:
# The number of elements.
g.size  

12

In [95]:
# The number of bytes used to represent one element.
g.itemsize  

8

In [97]:
# The number of dimensions.
g.ndim  

1

In [99]:
# The shape of the ndarray object.
g.shape  

(12,)

In [101]:
g.dtype  

dtype('float64')

In [103]:
# The total number of bytes used in memory.
g.nbytes  

96

### Reshaping, Resizing, Stacking, Flattening
Although ndarray objects are immutable by default, there are multiple options to reshape and resize such an object. While reshaping in general just provides another view on the same data, resizing in general creates a new (temporary) object. First, some examples of reshaping:

In [106]:
g = np.arange(15)

In [108]:
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [110]:
g.shape  

(15,)

In [112]:
np.shape(g) 

(15,)

In [114]:
# Reshaping to two dimensions (memory view).
g.reshape((3, 5))  

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [116]:
# Creating a new object.
h = g.reshape((5, 3))  
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [118]:
# The transpose of the new ndarray object.
h.T  

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [120]:
h.transpose()  

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

### Note
During a reshaping operation, the total number of elements in the ndarray object is unchanged. During a resizing operation, this number changes—it either decreases (“down-sizing”) or increases (“up-sizing”). Here some examples of resizing:

In [123]:
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [125]:
# Two dimensions, down-sizing.
np.resize(g, (3, 1))  

array([[0],
       [1],
       [2]])

In [127]:
np.resize(g, (1, 5))  

array([[0, 1, 2, 3, 4]])

In [129]:
np.resize(g, (2, 5))  

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [131]:
# Two dimensions, up-sizing.
n = np.resize(g, (5, 4))  
n

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14,  0],
       [ 1,  2,  3,  4]])

In [133]:
# Stacking is a special operation that allows the horizontal or vertical combination of
# two ndarray objects. However, the size of the “connecting” dimension must be the same:
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [135]:
# Horizontal stacking of two ndarray objects.
np.hstack((h, 2 * h))  

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16],
       [ 9, 10, 11, 18, 20, 22],
       [12, 13, 14, 24, 26, 28]])

In [137]:
# Vertical stacking of two ndarray objects.
np.vstack((h, 0.5 * h))  

array([[ 0. ,  1. ,  2. ],
       [ 3. ,  4. ,  5. ],
       [ 6. ,  7. ,  8. ],
       [ 9. , 10. , 11. ],
       [12. , 13. , 14. ],
       [ 0. ,  0.5,  1. ],
       [ 1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ],
       [ 4.5,  5. ,  5.5],
       [ 6. ,  6.5,  7. ]])

In [139]:
# Another special operation is the flattening of a multidimensional ndarray object to a
# one-dimensional one. One can choose whether the flattening happens row-by-row (C order)
# or column-by-column (F order):
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [141]:
# The default order for flattening is C.
h.flatten()  

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [143]:
h.flatten(order='C')  

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [145]:
# Flattening with F order.
h.flatten(order='F')  

array([ 0,  3,  6,  9, 12,  1,  4,  7, 10, 13,  2,  5,  8, 11, 14])

In [147]:
# The flat attribute provides a flat iterator (C order).
for i in h.flat:  
    print(i, end=',')

0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,

### Boolean Arrays
Comparison and logical operations in general work on ndarray objects the same way, element-wise, as on standard Python data types. Evaluating conditions yield by default a Boolean ndarray object (dtype is bool):

In [150]:
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [152]:
h > 8  

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [154]:
h <= 7  

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [156]:
h == 5  

array([[False, False, False],
       [False, False,  True],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [158]:
(h == 5).astype(int)  

array([[0, 0, 0],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [160]:
(h > 4) & (h <= 12)  

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True, False, False]])

In [162]:
# Such Boolean arrays can be used for indexing and data selection. Notice that the
# following operations flatten the data:
# Give me all values greater than 8:
h[h > 8]  

array([ 9, 10, 11, 12, 13, 14])

In [164]:
h[(h > 4) & (h <= 12)]  

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [166]:
h[(h < 4) | (h >= 12)]  

array([ 0,  1,  2,  3, 12, 13, 14])

In [168]:
# A powerful tool in this regard is the np.where() function, which allows the definition
# of actions/operations depending on whether a condition is True or False. The result
# of applying np.where() is a new ndarray object of the same shape as the original one:
# In the new object, set 1 if True and 0 otherwise:
np.where(h > 7, 1, 0)  

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [170]:
# In the new object, set even if True and odd otherwise.
np.where(h % 2 == 0, 'even', 'odd')  

array([['even', 'odd', 'even'],
       ['odd', 'even', 'odd'],
       ['even', 'odd', 'even'],
       ['odd', 'even', 'odd'],
       ['even', 'odd', 'even']], dtype='<U4')

In [172]:
# In the new object, set two times the h element if True and half the h element otherwise.
np.where(h <= 7, h * 2, h / 2)  

array([[ 0. ,  2. ,  4. ],
       [ 6. ,  8. , 10. ],
       [12. , 14. ,  4. ],
       [ 4.5,  5. ,  5.5],
       [ 6. ,  6.5,  7. ]])

### Structured NumPy Arrays
The specialization of the ndarray class obviously brings a number of valuable benefits with it. However, a too narrow specialization might turn out to be too large a burden to carry for the majority of array-based algorithms and applications. Therefore, NumPy provides structured ndarray and record recarray objects that allow you to have a different dtype per column. What does “per column” mean? Consider the following initialization of a structured ndarray object:

In [175]:
# The complex dtype is composed.
dt = np.dtype([('Name', 'S10'), ('Age', 'i4'),
               ('Height', 'f'), ('Children/Pets', 'i4', 2)])  

In [177]:
dt  

dtype([('Name', 'S10'), ('Age', '<i4'), ('Height', '<f4'), ('Children/Pets', '<i4', (2,))])

In [179]:
# An alternative syntax to achieve the same result.
dt = np.dtype({'names': ['Name', 'Age', 'Height', 'Children/Pets'],
             'formats':'O int float int,int'.split()})  

In [181]:
dt  

dtype([('Name', 'O'), ('Age', '<i8'), ('Height', '<f8'), ('Children/Pets', [('f0', '<i8'), ('f1', '<i8')])])

In [183]:
# The structured ndarray is instantiated with two records.
s = np.array([('Smith', 45, 1.83, (0, 1)),
              ('Jones', 53, 1.72, (2, 2))], dtype=dt)  

In [185]:
s  

array([('Smith', 45, 1.83, (0, 1)), ('Jones', 53, 1.72, (2, 2))],
      dtype=[('Name', 'O'), ('Age', '<i8'), ('Height', '<f8'), ('Children/Pets', [('f0', '<i8'), ('f1', '<i8')])])

In [187]:
type(s)  

numpy.ndarray

### Note:
In a sense, this construction comes quite close to the operation for initializing tables in a SQL database: one has column names and column data types, with maybe some additional information (e.g., maximum number of characters per str object). The single columns can now be easily accessed by their names and the rows by their index values:

In [190]:
s['Name']  

array(['Smith', 'Jones'], dtype=object)

In [192]:
s['Height'].mean()  

1.775

In [194]:
s[0]  

('Smith', 45, 1.83, (0, 1))

In [196]:
s[1]['Age']  

53

### Note:
In summary, structured arrays are a generalization of the regular ndarray object type in that the data type only has to be the same per column, like in tables in SQL databases. One advantage of structured arrays is that a single element of a column can be another multidimensional object and does not have to conform to the basic NumPy data types.

## Vectorization of Code
Vectorization is a strategy to get more compact code that is possibly executed faster. The fundamental idea is to conduct an operation on or to apply a function to a complex object “at once” and not by looping over the single elements of the object. In Python, functional programming tools such as map() and filter() provide some basic means for vectorization. However, NumPy has vectorization built in deep down in its core.

As demonstrated in the previous section, simple mathematical operations—such as calculating the sum of all elements—can be implemented on ndarray objects directly (via methods or universal functions). More general vectorized operations are also possible. For example, one can add two NumPy arrays element-wise as follows:

In [200]:
np.random.seed(100)
r = np.arange(12).reshape((4, 3))  
s = np.arange(12).reshape((4, 3)) * 0.5  

In [202]:
r  

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [204]:
s  

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ],
       [4.5, 5. , 5.5]])

In [206]:
r + s  

array([[ 0. ,  1.5,  3. ],
       [ 4.5,  6. ,  7.5],
       [ 9. , 10.5, 12. ],
       [13.5, 15. , 16.5]])

In [208]:
r + 3  

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [210]:
2 * r  

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [212]:
2 * r + 3  

array([[ 3,  5,  7],
       [ 9, 11, 13],
       [15, 17, 19],
       [21, 23, 25]])

In [214]:
r

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [216]:
r.shape

(4, 3)

In [218]:
s = np.arange(0, 12, 4)  
s  

array([0, 4, 8])

In [220]:
r + s  

array([[ 0,  5, 10],
       [ 3,  8, 13],
       [ 6, 11, 16],
       [ 9, 14, 19]])

In [222]:
s = np.arange(0, 12, 3)  
s  

array([0, 3, 6, 9])

In [224]:
# causes intentional error
# r + s  

In [226]:
r.transpose() + s  

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20]])

In [228]:
sr = s.reshape(-1, 1)  
sr

array([[0],
       [3],
       [6],
       [9]])

In [230]:
sr.shape  

(4, 1)

In [232]:
r + s.reshape(-1, 1)  

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14],
       [18, 19, 20]])

In [234]:
def f(x):
    return 3 * x + 5  

In [236]:
f(0.5)  

6.5

In [238]:
f(r)  

array([[ 5,  8, 11],
       [14, 17, 20],
       [23, 26, 29],
       [32, 35, 38]])

## Memory Layout

Cf. http://eli.thegreenplace.net/2015/memory-layout-of-multi-dimensional-arrays/

In [242]:
x = np.random.standard_normal((1000000, 5))  

In [244]:
y = 2 * x + 3  

In [246]:
C = np.array((x, y), order='C')  

In [248]:
F = np.array((x, y), order='F')  

In [250]:
x = 0.0; y = 0.0  

In [252]:
C[:2].round(2)  

array([[[-1.75,  0.34,  1.15, -0.25,  0.98],
        [ 0.51,  0.22, -1.07, -0.19,  0.26],
        [-0.46,  0.44, -0.58,  0.82,  0.67],
        ...,
        [-0.05,  0.14,  0.17,  0.33,  1.39],
        [ 1.02,  0.3 , -1.23, -0.68, -0.87],
        [ 0.83, -0.73,  1.03,  0.34, -0.46]],

       [[-0.5 ,  3.69,  5.31,  2.5 ,  4.96],
        [ 4.03,  3.44,  0.86,  2.62,  3.51],
        [ 2.08,  3.87,  1.83,  4.63,  4.35],
        ...,
        [ 2.9 ,  3.28,  3.33,  3.67,  5.78],
        [ 5.04,  3.6 ,  0.54,  1.65,  1.26],
        [ 4.67,  1.54,  5.06,  3.69,  2.07]]])

In [254]:
%timeit C.sum()  

1.15 ms ± 2.72 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [255]:
%timeit F.sum()  

1.16 ms ± 2.05 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [256]:
%timeit C.sum(axis=0)  

2.01 ms ± 5.81 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [260]:
%timeit C.sum(axis=1)  

14.4 ms ± 46.7 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [261]:
%timeit F.sum(axis=0)  

24.4 ms ± 41.4 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [262]:
%timeit F.sum(axis=1)  

22.4 ms ± 91.4 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [263]:
F = 0.0; C = 0.0  

<img src="http://hilpisch.com/tpq_logo.png" alt="The Python Quants" width="35%" align="right" border="0"><br>

<a href="http://tpq.io" target="_blank">http://tpq.io</a> | <a href="http://twitter.com/dyjh" target="_blank">@dyjh</a> | <a href="mailto:training@tpq.io">training@tpq.io</a>